### ISSUE TITLE
缺少libext_xxtea.dylib文件

### ISSUE THREAD

**Issue by F1uYu4n** [TeamRocketIst/cocos2d-dec#1]
求教，/cocos2d-dec/lib/libext_xxtea.dylib: cannot open shared object file: No such file or directory 这个报错中的libext_xxtea.dylib文件如何生成？

**Comment by Hunt3rKun** [comment]
dylib是Mac的动态库，linux下的就是.so 把代码里面的这个后缀改一下就行了

**Comment by F1uYu4n** [comment]
谢谢，问题顺利解决
